version: "3.3"
services:
  db:
    image: postgres:latest
    container_name: xappdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0110
      POSTGRES_DB: xappdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: xappcore
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres_data:
